spring:
  application:
    name: ddns-service

logging:
  level:
    root: info
    com.imjcker: info
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} -%5p [%t] %-40.40logger{39} : %X{uuid} %m%n"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} -%5p [%t] %-40.40logger{39} : %X{uuid} %m%n"
  file:
    name: ${user.dir}/logs/${spring.application.name}.log

ddns:
  job:
    cron: "0 */2 * * * ?"
  ip-fetch-url: http://ip.sb
  headers:
    X-auth-Email: ${X-AUTH-EMAIL:helloalanturing@icloud.com}
    X-auth-Key: ${X-AUTH-KEY:639164cf0ab9e7652ad48ce90c061e787cfa8}
    Content-Type: ${CONTENT-TYPE:application/json}

  params:
    type: ${DDNS-TYPE:A}
    name: ${DDNS-NAME:imjcker.com}
    ttl: ${DDNS-TTL:120}
    proxied: ${DDNS-PROXIED:false}

